[package]
name = "connectivity"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.79"
fs-err = "2.11.0"
geo = { version = "0.27.0", default-features = false }